remove cmake install and only install ninja
- also add version parameter for ninja
- switch to only using tool-cache for caching

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -15,38 +15,30 @@ jobs:
       fail-fast: false
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
+        version: [ '1.9.0', '1.10.2' ]
 
     steps:
-    - uses: actions/checkout@v1
+    - uses: actions/checkout@v2
       with:
         submodules: true
-    - uses: actions/setup-node@v1
+    - uses: actions/setup-node@v2
       with:
-        node-version: '12.x'
+        node-version: '12'
     - run: |
         npm install
         npm run test
       name: build and test
     - uses: ./
-      name: validation test by running get-cmake
-    - name: CMake version check
-      run: |
-        which cmake
-        cmake --version
-        CMAKE_VER="$(cmake --version)"
-        if ! [[ "$CMAKE_VER" =~ .*"3.21.2".* ]]; then
-          echo "ASSERTION FAILED! Instead of 3.21.2, found: "
-          echo "$CMAKE_VER"
-          exit -1
-        fi
-      shell: bash
+      name: validation test by running action-get-ninja
+      with:
+        version: '${{ matrix.version }}'
     - name: ninja version check
       run: |
         which ninja
         ninja --version
         NINJA_VER="$(ninja --version)"
-        if ! [[ "$NINJA_VER" =~ .*"1.10.2".* ]]; then
-          echo "ASSERTION FAILED! Instead of 1.10.2, found: "
+        if ! [[ "$NINJA_VER" == "${{ matrix.version }}" ]]; then
+          echo "ASSERTION FAILED! Instead of ${{ matrix.version }}, found: "
           echo "$NINJA_VER"
           exit -1
         fi
